# Dependabot Configuration for Miyao Bot
# Automated dependency updates to keep dependencies secure and up-to-date

version: 2

updates:
  # NPM Dependencies (Main Bot)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 10
    
    # Auto-merge rules
    # Patch and minor updates can be auto-merged after tests pass
    allow:
      - dependency-type: "all"
    
    # Grouping strategy
    groups:
      # Group all patch updates together
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      
      # Group minor updates of development dependencies
      dev-minor-updates:
        dependency-type: "development"
        update-types:
          - "minor"
    
    # Commit message preferences
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    
    # Labels for PRs
    labels:
      - "dependencies"
      - "automated"
    
    # Review configuration
    reviewers:
      - "khuongl24"
    
    # Ignore specific updates (if needed)
    ignore:
      # Ignore major version updates for stable packages
      # Uncomment to ignore specific packages
      # - dependency-name: "discord.js"
      #   update-types: ["version-update:semver-major"]
    
    # Pull request limits
    target-branch: "main"
    
  # NPM Dependencies (Launcher)
  - package-ecosystem: "npm"
    directory: "/launcher-v2"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 5
    
    commit-message:
      prefix: "deps(launcher)"
    
    labels:
      - "dependencies"
      - "launcher"
      - "automated"
    
    reviewers:
      - "khuongl24"
    
  # NPM Dependencies (Master Setup)
  - package-ecosystem: "npm"
    directory: "/master-setup"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 5
    
    commit-message:
      prefix: "deps(setup)"
    
    labels:
      - "dependencies"
      - "setup-tools"
      - "automated"
    
    reviewers:
      - "khuongl24"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Ho_Chi_Minh"
    
    commit-message:
      prefix: "ci"
    
    labels:
      - "ci/cd"
      - "automated"
    
    reviewers:
      - "khuongl24"

# Additional Notes:
# 
# 1. Schedule:
#    - Weekly updates on Monday at 3 AM (Vietnam time)
#    - Reduces noise while keeping dependencies fresh
#    - Monday allows review during work week
#
# 2. Grouping Strategy:
#    - Patch updates grouped together (easier to review)
#    - Dev dependencies grouped separately
#    - Reduces number of PRs
#
# 3. Security:
#    - Security updates are always created immediately (Dependabot default)
#    - Critical vulnerabilities bypass schedule
#
# 4. Auto-merge Consideration:
#    - Patch updates can be auto-merged if tests pass
#    - Requires GitHub Actions workflow setup
#    - See: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
#
# 5. Monitoring:
#    - Check Insights > Dependency graph > Dependabot
#    - Review PRs weekly
#    - Test before merging major updates
#
# 6. Best Practices:
#    - Always run tests before merging
#    - Review CHANGELOG for breaking changes
#    - Keep Node.js version updated (>=20.0.0)
#    - Monitor Discord.js for API changes
